In [3]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
data = [1,2,3,4]
array = np.array(data)

In [8]:
array

array([1, 2, 3, 4])

In [9]:
ndimensionsal_array= np.array([[1,2,3],[4,5,6]])

In [11]:
ndimensionsal_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
ndimensionsal_array_01=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
ndimensionsal_array_01

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
ndimensionsal_array_02= np.eye(3,3)

In [19]:
ndimensionsal_array_02

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
ndimensionsal_array_03= np.zeros((3,2))

In [25]:
ndimensionsal_array_03

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
ndimensionsal_array_04 =np.ones((3,3))

In [29]:
ndimensionsal_array_04

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])